branches:
    - "+([0-9])?(.{+([0-9]),x}).x"
    - main
    - next
    - next-major
    - name: beta
      prerelease: true
    - name: alpha
      prerelease: true

plugins:
    - "@semantic-release/commit-analyzer"
    - "@semantic-release/release-notes-generator"
    - "@semantic-release/changelog"
    - - "@semantic-release/npm"
      - pkgRoot: "./package"
    - - "@semantic-release/git"
      - assets: ["CHANGELOG.md"]
        message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    - - "@semantic-release/github"
      - assets:
            - path: "svelte-codemirror-editor.zip"
              name: "svelte-codemirror-editor-v${nextRelease.version}.zip"
